<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="propdsl" nsURI="http://www.eclipse.org/sirius/project/propdsl"
    nsPrefix="propdsl">
  <eClassifiers xsi:type="ecore:EClass" name="Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formula" lowerBound="1"
        upperBound="-1" eType="#//Formula" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Formula" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="root" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//BooleanObject"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Proposition" eSuperTypes="#//Formula">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinOp" eSuperTypes="#//Formula">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="btype" eType="#//BinOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bformula" lowerBound="2"
        upperBound="2" eType="#//Formula"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnOp" eSuperTypes="#//Formula">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="utype" eType="#//UnOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uformula" lowerBound="1"
        eType="#//Formula"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinOperator">
    <eLiterals name="AND"/>
    <eLiterals name="OR" value="1"/>
    <eLiterals name="IF" value="2"/>
    <eLiterals name="IFF" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnOperator">
    <eLiterals name="NOT"/>
  </eClassifiers>
</ecore:EPackage>
